все задания сделаны в отдельных паках в отдельных классах
Sunl1t/Homework_SberTech pull request #2
Opened 2024-07-02 22:42 UTC by Sunl1t

2024-07-03 14:41 UTC, XLelarX requested changes

2024-07-03 14:41 UTC, XLelarX commented on src/third/Matrix.java
> +            throw new IllegalArgumentException("Матрицы не могут быть перемножены из-за несовместимых размеров");
`"Матрицы не могут быть перемножены из-за несовместимых размеров"` такие строки нужно делать константами (private static final CONST_NAME)

2024-07-03 14:41 UTC, XLelarX commented on src/first/Phone.java
> +        this.number = number;
здесь this(number, model)

2024-07-03 14:41 UTC, XLelarX commented on src/first/Phone.java
> +    public String toString()
`@Override` аннотацию для всех переопределенных методов надо проставлять (включая переопределение Object методов)

2024-07-03 14:41 UTC, XLelarX commented on src/first/Phone.java
> +    public String toString()
делай пробел между методами плз

2024-07-03 14:41 UTC, XLelarX commented on src/first/Phone.java
> +        return (number + " " + model + " " + weight);
`( )` избыточны

2024-07-03 14:41 UTC, XLelarX commented on src/first/Phone.java
> +        return (number + " " + model + " " + weight);
В других подобных местах тоже

2024-07-03 14:41 UTC, XLelarX commented on src/first/Phone.java
> +    public String toString()
В других подобных местах тоже

2024-07-03 14:41 UTC, XLelarX commented on src/second/Circle.java
> +    static double PI = 3.14159265358979323846;
Есть Math.PI. Заюзай его

2024-07-03 14:41 UTC, XLelarX commented on src/second/Circle.java
> +public class Circle {
А зачем этот класс?

2024-07-03 14:41 UTC, XLelarX commented on src/sixth/Square.java
> +    public String toString() {
Придерживайся одного стиля в реализациях toString()

2024-07-03 16:32 UTC, Sunl1t reviewed
fixed

2024-07-04 19:06 UTC, XLelarX approved these changes

2024-07-04 19:06 UTC, XLelarX commented on .idea/uiDesigner.xml
Убери плз из изменений файлик

2024-07-04 19:06 UTC, XLelarX commented on .idea/workspace.xml
Убери плз из изменений файлик

2024-07-04 19:06 UTC, XLelarX commented on HW2.iml
Убери плз из изменений файлик

2024-07-04 19:19 UTC, merged